### ISSUE TITLE
Where are the tags for specific addresses stored?

### ISSUE THREAD

**Issue by Robyer** [12remember/quantascan-backend#16]
I wanted to update some known QRL addresses, but I am unable to find it in quantascan-backend and quantascan-frontend repositories.

It would be good to have the tags fixed in some file so we can update it through PR.

What I wanted to set are these:

- Q000500997c93dec6039f0fb6008bbf034bc4f9252f6cfd41a7e01c8cf934036deaa4a832c4f240 - QRL foundation reserve (as seen on https://www.theqrl.org/tokenomics/ )
- Q010500b8601fb018af63f22b31854f649f32249ffd7c2e887d80694b458bd18ee6ca9f9806c016 - MEXC.com exchange
- Q010300c1ff9655c6d90eb0d8e7c2514bf60a1ee64182be2073c103455db9576de1cf1e1c6fa956 - LBank.com exchange
- Q010500001e767b586e701c4139ffa7521aff6e9e34ec5cd8b3e596dbbf9f72a6d0595f6f886e92 - XT.com exchange

**Comment by 12remember** [comment]
Hi,

They are stored in the Postgres db (wallet table ). The call can be found here : 

quantascan-backend/analytics/views.py

class walletRichList > qs = 

then 'wallet_custom_name'


I have inserted the new wallet names

Thank you :)
